---
- name: Template with a loop Challenge
  hosts: fry
  connection: ansible.builtin.ssh
  gather_facts: true 

  vars_files:
  - vars/challenge03.yml

  tasks:
  - name: Running a looping jinja template with external vars file
    ansible.builtin.template: 
      src: templates/mission-orders.txt.j2
      dest: "~/{{ item.mission }}-mission-orders.txt"  # name of the completed file to be placed on the target system
    loop: "{{ objectives }}"
    vars:
      planet: "{{ item.planet }}"

